spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ride_db
    username: ride_user
    password: ride_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8082

jwt:
  secret: "your-ride-service-jwt-secret-key"
  expiration: 3600000

logging:
  level:
    org.springframework: INFO
