spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ride_db
    driver-class-name: org.postgresql.Driver
    username: ride_user
    password: ride_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8082